def return_colors():
    color_ttype = {  'Breast':'#fa9fb5',
                     'Colon-Rectum': '#053061',
                     'Prostate':'#7fbf7b',
                     'Lung':'#ffc900ff',
                     'Skin':'black',
                     'Bone-Soft-tissue':'#ff6600ff',
                     'Ovary':'#f03b20',
                     'Esophagus':'#fdae61',
                     'Urinary-tract':'#543005',
                     'NET':'#542788',
                     'Kidney':'#b8e186',
                     'Nervous-system':'#abd9e9',
                     'Biliary':'#1a9850',
                     'Pancreas':'#fdae61',
                     'Unknown':'grey',
                     'Uterus':'#f4a582',
                     'Head-and-neck':'#99d8c9',
                     'Liver':'#d53e4f',
                     'Stomach':'#fde0ef',
                     'Mesothelioma':'#4d4d4d',
                     'Lymphoid':'#35978f',
                     'Thyroid':'#ffffbf',
                     'Small-intestine':'#fccde5',
                     'Vulva':'#bc80bd',
                     'Testis':'#ccebc5',
                     'Penile':'#8dd3c7',
                     'Thymus':'darkgreen',
                     'Adrenal':'#f768a1',
                     'Myeloid':'#f7f4f9',
                     'Double-primary':'grey',
                     'nan':'#fee8c8'
                  }
    return color_ttype
