import sys
import os

import pandas as pd

scripts_path = os.path.abspath(os.path.join(__file__, '..', '..'))
sys.path.insert(0, scripts_path)
from config import Conf


def return_metadata():

    file_metadata = Conf['path_metadata']
    pat = pd.read_csv(file_metadata, sep='\t')

    pat['primaryTumorLocation'] = pat['primaryTumorLocation'].replace('Bone/soft tissue', 'Bone/Soft tissue')

    # fix primary location
    pat['primaryTumorLocation_fixed'] = pat['primaryTumorLocation'].apply(
        lambda x: str(x).replace(' ', '-').replace('/', '-')
    )
    pat['primaryTumorLocation_fixed'] = pat['primaryTumorLocation_fixed'].replace('Head-and-Neck', 'Head-and-neck')
    pat['primaryTumorLocation_fixed'] = pat['primaryTumorLocation_fixed'].replace('nan', 'Unknown')
    pat['primaryTumorLocation_fixed'] = pat['primaryTumorLocation_fixed'].replace('CUP', 'Unknown')
    pat['primaryTumorLocation_fixed'] = pat['primaryTumorLocation_fixed'].replace('Net', 'NET')

    pat['merged'] = pat['primaryTumorLocation'].astype(str) + '_' + pat['cancerSubtype'].astype(str)
    pat['secondaryTumorLocation_fixed'] = pat['merged'].map(d_second)
    dic_primary_full = dict(zip(pat.sampleId, pat.primaryTumorLocation_fixed))
    dic_secondary_fixed = dict(zip(pat.sampleId, pat.secondaryTumorLocation_fixed))

    return dic_primary_full, dic_secondary_fixed


# dictionary with second locations, not currently needed
d_second = {
    'Head and neck_Ceruminous glands': 'Head-and-neck',
    'Small intestine_Ilium': 'SI',
    'Bone/Soft tissue_Myofibroblastar sarcoma': 'Sarcoma',
    'Bone/Soft tissue_Osteosarcoma (Bone Cancer)': 'Osteosarcoma',
    'Bone/Soft tissue_Solitary fibrous tumor': 'Sarcoma',
    'Bone/Soft tissue_Spindle cell sarcoma': 'Sarcoma',
    'Bone/Soft tissue_Synovial': 'Sarcoma',
    'Bone/Soft tissue_Undifferentiated sarcoma': 'Sarcoma',
    'Bone/soft tissue_Cutaneous angiosarcoma': 'Sarcoma',
    'CUP_nan': 'Unknown',
    'Colon/Rectum_Colon': 'ColoRectal',
    'Colon/Rectum_Low-grade mucinous adenocarcinoma': 'ColoRectal',
    'Colon/Rectum_Rectum': 'ColoRectal',
    'Eye_Melanoma': 'Skin-UvealMelanoma',
    'Head and Neck_Oropharynx': 'Head-and-neck',
    'Head and neck_External auditory canal': 'Head-and-neck',
    'Liver_Other: hepatocellular or cholangiocarcinoma': 'Luver-Other',
    'Lung_Small cell lung carcinoma (SCLC)': 'Lung-SC',
    'Lung_nan': 'Lung-Unknown',
    'Lymphoid_Hodgkin': 'Lymph-H',
    'Lymphoid_Non-Hodgkin': 'Lymph-NH',
    'Lung_Trachea': 'Lung-Trachea',
    'Urinary tract_Unknown': 'UT',
    'Urinary tract_Pyelum and Urethra': 'UT',
    'Unknown_Biliary tract': 'Biliary',
    'Small intestine_Jejunum': 'SI',
    'Skin_Merkel-cell': 'Skin-Other',
    'NET_Prostate': 'Prostate-NET',
    'Ovary_Left tuba': 'Ovary',
    'NET_Small Intestinal': 'SI-NET',
    'NET_Rectosigmoid': 'ColoRectal-NET',
    'NET_Rectum': 'ColoRectal-NET',
    'Nervous system_Meningeoma': 'CNS-Other',
    'Nervous system_Medulloblastoma': 'CNS-Other',
    'NET_Possible transformation of prostatecarcinoma': 'Prostate-NET',
    'NET_Bladder': 'NET-Bladder',
    'NET_Cervix': 'Cervix-NET',
    'NET_Pancreatic': 'Pancreas-NET',
    'Ovary_Serous carcinoma': 'Ovary',
    'Bone/Soft tissue_Gastrointestinal stromal tumor (GIST)': 'GIST',
    'Prostate_nan': 'Prostate',
    'Unknown_CUP': 'Unknown',
    'Breast_ER-positive/HER2-negative': 'Breast',
    'NET_Small instentine': 'SI-NET',
    'Lung_Non-Small cell': 'Lung-NSC',
    'Breast_nan': 'Breast',
    'Bone/Soft tissue_Sarcoma': 'Sarcoma',
    'Skin_Melanoma': 'Skin-Melanoma',
    'Liver_nan': 'Liver',
    'NET_Lung': 'Lung-NET',
    'Biliary_Gall bladder': 'Biliary',
    'Biliary_Cholangiocarcinoma': 'Biliary',
    'Bone/Soft tissue_Angiosarcoma': 'Sarcoma',
    'Colon/Rectum_nan': 'ColoRectal',
    'Urinary tract_Urethra': 'UT',
    'Bone/Soft tissue_Leiomyosarcoma': 'Leiomyosarcoma',
    'Ovary_nan': 'Ovary',
    'Lung_Small Cell': 'Lung-SC',
    'Kidney_Renal cell': 'Kidney-RC',
    'Breast_Triple negative': 'Breast',
    'NET_Pancreas': 'Pancreas-NET',
    'NET_nan': 'Unknown',
    'Breast_Subtype unknown': 'Breast',
    'Breast_ER-negative/HER2-positive': 'Breast',
    'Esophagus_nan': 'Esophagus',
    'Stomach_nan': 'Stomach',
    'NET_Colon/Rectum': 'ColoRectal-NET',
    'Mesothelioma_nan': 'Mesothelioma',
    'Thymus_nan': 'Thymus',
    'Breast_ER-positive/HER2-positive': 'Breast',
    'Urinary tract_Bladder': 'Bladder',
    'Bone/Soft tissue_Liposarcoma': 'Sarcoma',
    'Skin_Skin squamous cell carcinoma': 'Skin-SCC',
    'Uterus_Endometrial': 'Uterus',
    'Urinary tract_Other': 'UT',
    'nan_nan': 'Unknown',
    'Lung_Mix of SCLC & NSCLC': 'Lung-NSC',
    'Liver_Hepatocellular': 'Liver',
    'Thyroid_nan': 'Thyroid',
    'Head and neck_Lip and Oral Cavity': 'Head-and-neck',
    'Uterus_Cervical': 'Uterus',
    'Vulva_nan': 'Vulva',
    'Bone/Soft tissue_Rhabdomyosarcoma': 'Rhabdomyosarcoma',
    'Breast_ER-positive/HER2 unknown': 'Breast',
    'Bone/Soft tissue_Desmoid': 'Sarcoma',
    'Bone/Soft tissue_Osteosarcoma': 'Osteosarcoma',
    'Head and neck_Salivary Gland': 'Head-and-neck',
    'Pancreas_nan': 'Pancreas',
    'Liver_Mixed Hepatocellular and Cholangio': 'Liver',
    'Nervous system_Glioma': 'CNS-Glioma',
    'NET_Lung or small intenstine': 'SI-NET',
    'Urinary tract_Pyelum': 'UT',
    'Double primary_Bladder and Mesothelioma': 'Bladder',
    'NET_Paraganglioma (lung?)': 'Lung-NET',
    'Head and neck_Oropharyngeal': 'Head-and-neck',
    'Colon/Rectum_Anal': 'ColoRectal',
    'Head and neck_Hypopharyngeal': 'Head-and-neck',
    'Head and neck_nan': 'Head-and-neck',
    'Lymphoid_Hodgkin lymphoma': 'Lymph-H',
    'Stomach_Cardiacarcinoma': 'Stomach',
    'Head and neck_Laryngeal': 'Head-and-neck',
    'Double primary_Endometrial and Ovarian': 'Ovary',
    'Head and neck_Tongue': 'Head-and-neck',
    'Nervous system_Glioblastoma Multiforme': 'CNS-Glioma',
    'Nervous system_Glioma: anaplastic astrocytoma-like': 'CNS-Astro',
    'Colon/Rectum_Appendix': 'ColoRectal',
    'Skin_Basal cell carcinoma': 'Skin-BCC',
    'Ovary_Extra ovarial serous carcinoma': 'Ovary',
    'Lung_Adenocarcinoma': 'Lung-AdenoCa',
    'Colon/Rectum_Tubulovilleus Adenoma': 'ColoRectal',
    'Head and neck_Nasal cavity and paranasal sinuses': 'Head-and-neck',
    'Nervous system_Neuroblastoma': 'CNS-Neuro',
    'Bone/Soft tissue_Carcinosarcoma': 'Sarcoma',
    'Adrenal_Pheochromocytoma': 'Pheochromocytoma',
    'Colon/Rectum_Ascending': 'ColoRectal',
    'Skin_Atypical Fibroxanthoma': 'Skin-Other',
    'Small intestine_Adenocarcinoma': 'SI',
    'Testis_nan': 'Testis',
    'Head and neck_Nasopharyngeal': 'Head-and-neck',
    'Skin_nan': 'Skin-unknown',
    'Penile_nan': 'Penile',
    'Skin_Sweat glands': 'Skin-Other',
    'Biliary_Ampulla of Vater or distal choledochus': 'Biliary',
    'Bone/Soft tissue_Ewing sarcoma': 'Sarcoma',
    'Lung_Adenoid Cystic': 'Lung-AdenoCa',
    'Unknown_Adenocarcinoma': 'Unknown',
    'Unknown_Possibly Head and neck': 'Unknown',
    'Mesothelioma_Pericarditis carcinomatosa': 'Mesothelioma',
    'Unknown_Probably rectum': 'ColoRectal',
    'Nervous system_Plexuspapilloom': 'CNS-Other',
    'Bone/Soft tissue_Chondrosarcoma': 'Sarcoma',
    'Urinary tract_Urachal carcinoma': 'UT',
    'Adrenal_nan': 'Adrenal',
    'Nervous system_Glioma: anaplastic oligodendroglioma-like': 'CNS-Glioma',
    'NET_Large cell': 'Lung-NET',
    'Bone/Soft tissue_Carcinosarcoma (Uterus)': 'Sarcoma',
    'Esophagus_Esophagus-Gastric junction': 'Esophagus',
    'Liver_Cystadenocarcinoma': 'Liver',
    'Biliary_Choledochuscarcinoma': 'Biliary',
    'Nervous system_Solitair fibreuze tumor in brain': 'CNS-Other',
    'Nervous system_Oligodendroglioma': 'CNS-Oligo',
    'Bone/Soft tissue_Uterine sarcoma': 'Sarcoma',
    'Nervous system_Astrocytoma': 'CNS-Astro',
    'Vulva_Squamous cell carcinoma in the vagina': 'Vulva',
    'Lymphoid_Other': 'Lymph-Other',
    'Small intestine_Mixed NET/non-NET': 'SI',
    'NET_Gastrinoma': 'Stomach-NET',
    'Small intestine_Duodenum': 'SI',
    'Unknown_Myoepithelial carcinoma': 'Unknown',
    'Colon/Rectum_Sigmoid': 'ColoRectal',
    'NET_Thymus': 'Thymus-NET',
    'Stomach_Non-Small cell NHL': 'Stomach',
    'NET_Non-Small cell': 'Lung-NET',
    'Stomach_Gastric': 'Stomach',
    'Myeloid_Multiple Myeloma: Morbus Kahler': 'Myeloma',
    'Lymphoid_Non-Hodgkin lymphoma': 'Lymph-NH',
    'Kidney_nan': 'Kidney',
    'Myeloid_Multiple Myeloma': 'Myeloma',
    'Ovary_Tuba': 'Ovary',
    'Unknown_Gall bladder, pancreas or biliary tract': 'Unknown',
    'Unknown_Possibly SCLC': 'Unknown',
    'Skin_Merkelcell carcinoma': 'Skin-Other',
    'Unknown_Most likely high tractus digestive tumor': 'Unknown',
    'Uterus_Probably Endometrium': 'Unknown',
    'Unknown_Tractus Genitalis': 'Unknown',
    'Bone/Soft tissue_Inflammatory myofibroblastic sarcoma': 'Sarcoma',
    'Head and neck_Salivary Duct': 'Head-and-neck'
}
